[package]
name = "vban-server"
version = "0.1.0"
edition = "2024"
authors = ["PipeMeeter Team <dev@pipemeeter.org>"]
description = "Asynchronous / UDP server implementation for VBAN control and real-time state streams"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pipemeeter/vban-server"

[lib]
name = "vban_server"
path = "src/lib.rs"

[dependencies]
vban-common = { version = "0.1.0", path = "../vban-common", default-features = false }
log = "0.4"

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_precision_loss = "allow"
cast_possible_truncation = "allow"
similar_names = "allow"
